import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

final kHeight5 = SizedBox(height: 5.sp);
final kHeight10 = SizedBox(height: 10.sp);
final kHeight15 = SizedBox(height: 15.sp);
final kHeight20 = SizedBox(height: 20.sp);
final kHeight25 = SizedBox(height: 25.sp);
final kHeight30 = SizedBox(height: 30.sp);
final kHeight35 = SizedBox(height: 35.sp);
final kHeight40 = SizedBox(height: 40.sp);
final kHeight45 = SizedBox(height: 45.sp);
final kHeight50 = SizedBox(height: 50.sp);
final kHeight55 = SizedBox(height: 55.sp);
final kHeight60 = SizedBox(height: 60.sp);
final kHeight65 = SizedBox(height: 65.sp);
final kHeight70 = SizedBox(height: 70.sp);
final kHeight75 = SizedBox(height: 75.sp);
final kHeight80 = SizedBox(height: 80.sp);
final kHeight85 = SizedBox(height: 85.sp);
final kHeight90 = SizedBox(height: 90.sp);
final kHeight95 = SizedBox(height: 95.sp);
final kHeight100 = SizedBox(height: 100.sp);

final kWidth5 = SizedBox(width: 5.sp);
final kWidth10 = SizedBox(width: 10.sp);
final kWidth15 = SizedBox(width: 15.sp);
final kWidth20 = SizedBox(width: 20.sp);
final kWidth25 = SizedBox(width: 25.sp);
final kWidth30 = SizedBox(width: 30.sp);
final kWidth35 = SizedBox(width: 35.sp);
final kWidth40 = SizedBox(width: 40.sp);
final kWidth45 = SizedBox(width: 45.sp);
final kWidth50 = SizedBox(width: 50.sp);
final kWidth55 = SizedBox(width: 55.sp);
final kWidth60 = SizedBox(width: 60.sp);
final kWidth65 = SizedBox(width: 65.sp);
final kWidth70 = SizedBox(width: 70.sp);
final kWidth75 = SizedBox(width: 75.sp);
final kWidth80 = SizedBox(width: 80.sp);
final kWidth85 = SizedBox(width: 85.sp);
final kWidth90 = SizedBox(width: 90.sp);
final kWidth95 = SizedBox(width: 95.sp);
final kWidth100 = SizedBox(width: 100.sp);